env:
  browser: true
  es2021: true
  jasmine: true
extends:
  - standard
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
plugins:
  - '@typescript-eslint'
rules: {
  no-unused-vars: "off"
}
