# Node setup
language: node_js

services:
  - postgresql

# Versiones de node en las que funciona la aplicación
node_js:
  - 14

# Instalación de dependencias
install:
  - npm ci

before_script:
  - psql -c 'create database test;' -U postgres
  - psql -c "ALTER USER postgres PASSWORD 'testdb';" -U postgres
  - psql -c 'GRANT ALL PRIVILEGES ON DATABASE test TO postgres;' -U postgres
  - psql -d postgres://$DB_USER:$DB_PASSWORD@$DB_HOST:$DB_PORT/$DB_NAME -d database/tables.sql

env:
  global:
    - DB_NAME: test
    - DB_USER: postgres
    - DB_PASSWORD: testdb
    - DB_HOST: localhost
    - DB_PORT: 5432
    - JWT_SECRET: aSecretKey

# Ejecución de los tests
script:
  - npm test
