# Node setup
language: node_js

# Versiones de node en las que funciona la aplicación
node_js:
    - 14
    - 13
    - 12
    - 11
    - 10

# Instalación de dependencias
install:
    - npm ci

# Ejecución de los tests
script:
    - npm test
