version: "3.8"

services:
  footstats:
    depends_on:
      - db
    image: ghcr.io/manueljnunez/footstats:latest
    volumes:
      - "$PWD:/test"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
      DB_PORT: 5432
      JWT_SECRET: aSecretKey

  db:
    image: postgres:alpine
    restart: always
    volumes:
      - ./database/tables.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
