name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.SECRET_KEY }}
        registry: ghcr.io
        repository: manueljnunez/footstats
        tags: latest
    - name: Obteniendo y ejecutando contendor
      run: docker run -t -v `pwd`:/test docker.pkg.github.com/manueljnunez/footstats/footstats:latest
