name: Node.js CI & Autobuild

on: [push]

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.check.outputs.container }}

    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        name: Buscando cambios en el Dockerfile o package.json 🔍
        id: check
        with:
          filters: |
            container:
              - 'Dockerfile'
              - 'package.json'
        

  build-and-push:
    runs-on: ubuntu-latest
    needs: check-changes
    if: needs.check-changes.outputs.changed == 'true'

    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login en GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.SECRET_KEY }}
          registry: ghcr.io
      - name: Build y push hacia GHCR
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/manueljnunez/footstats:latest
      

  test:
    runs-on: ubuntu-latest
    needs: build-and-push
    if: ${{ always() }}

    steps:
    - name: Login
      uses: docker/login-action@v1
      with:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.SECRET_KEY }}
        registry: ghcr.io
    - uses: actions/checkout@v2
    - name: Obteniendo y ejecutando contenedor 🧪
      run: docker run -t -v `pwd`:/test ghcr.io/manueljnunez/footstats:latest
