name: Firebase CD

on:
  push:
    paths:
      - 'telegram/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Install Dependencies
        run: npm ci
        working-directory: ./telegram/functions
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_PATH: "./telegram"
