name: "Build & Push to GHCR"

on:
  push:
    paths:
      - 'Dockerfile'
      - 'package.json'

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        needs: check-changes
        if: needs.check-changes.outputs.changed == 'true'
    
        steps:
          - uses: actions/checkout@v2
          - name: Set up QEMU
            uses: docker/setup-qemu-action@v1
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v1
          - name: Login en GitHub Container Registry
            uses: docker/login-action@v1 
            with:
              username: ${{ github.repository_owner }}
              password: ${{ secrets.SECRET_KEY }}
              registry: ghcr.io
          - name: Build y push hacia GHCR
            id: docker_build
            uses: docker/build-push-action@v2
            with:
              push: true
              tags: ghcr.io/manueljnunez/footstats:latest
          - name: Image digest
            run: echo ${{ steps.docker_build.outputs.digest }}