name: linter
on: push
jobs:
  ESlint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Instalación de los módulos
      run: npm install
    - name: Ejecutar ESLint
      run: npm run lint

  hadolint:
    runs-on: ubuntu-latest

    steps:
      uses: brpaz/hadolint-action@master