name: linter

on: 
  push:
    paths:
      - 'Dockerfile'
      - 'src/'
      - 'tests/'
  
  pull_request:
    paths:
      - 'Dockerfile'
      - 'src/'
      - 'tests/'

jobs:
  ESlint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Instalación de los módulos
      run: npm install
    - name: Ejecutar ESLint
      run: npm run lint

  hadolint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: "Ejecutar hadolint"
        uses: brpaz/hadolint-action@master
        with:
          dockerfile: "Dockerfile"

