name: "Comprueba README"

on:
  push:
    paths:
      - 'README.md'
      - 'words.dic'

  pull_request:
    paths:
      - 'README.md'
      - 'words.dic'

jobs:
  OrtografiaReadme:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        apt-get update && apt-get upgrade -y && apt-get install -y libtext-hunspell-perl
        pip install pyspelling
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Check README spell
      run: |
        pyspelling -c .spellcheck.yml
