name: "Comprueba README"

on:
  push:
    paths:
      - 'README.md'
      - 'words.dic'

  pull_request:
    paths:
      - 'README.md'
      - 'words.dic'

jobs:
  OrtografiaReadme:
    runs-on: ubuntu-latest

    container:
      image: python:3.8

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        apt-get update && apt-get install -y aspell-es
        pip install 'pyspelling==2.6.1'
    - name: Check README
      run: |
        pyspelling -c .spellcheck.yml
