name: "Comprueba README"

on:
  push:
    paths:
      - 'README.md'
      - 'words.dic'

  pull_request:
    paths:
      - 'README.md'
      - 'words.dic'

jobs:
  OrtografiaReadme:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: rojopolis/spellcheck-github-actions@0.5.0
      name: Checkear ortografía README