name: "Actualiza datos LaLiga"

on:
  schedule:
    - cron: '0 0 * * *'

env:
  RAPIDAPI_KEY: ${{ secrets.REPIDAPI_KEY }}

jobs:
  updatedata:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Data update
        run: ./.github/workflows/get-data.sh
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "LaLiga-Bot"
          git add functions/data.js
          git commit -m "Actualizados los datos de LaLiga"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
